// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import filestore "github.com/kbase/blobstore/filestore"
import mock "github.com/stretchr/testify/mock"

// FileStore is an autogenerated mock type for the FileStore type
type FileStore struct {
	mock.Mock
}

// CopyFile provides a mock function with given fields: sourceID, targetID
func (_m *FileStore) CopyFile(sourceID string, targetID string) error {
	ret := _m.Called(sourceID, targetID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(sourceID, targetID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteFile provides a mock function with given fields: id
func (_m *FileStore) DeleteFile(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetFile provides a mock function with given fields: id
func (_m *FileStore) GetFile(id string) (*filestore.GetFileOutput, error) {
	ret := _m.Called(id)

	var r0 *filestore.GetFileOutput
	if rf, ok := ret.Get(0).(func(string) *filestore.GetFileOutput); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*filestore.GetFileOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StoreFile provides a mock function with given fields: p
func (_m *FileStore) StoreFile(p *filestore.StoreFileParams) (*filestore.StoreFileOutput, error) {
	ret := _m.Called(p)

	var r0 *filestore.StoreFileOutput
	if rf, ok := ret.Get(0).(func(*filestore.StoreFileParams) *filestore.StoreFileOutput); ok {
		r0 = rf(p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*filestore.StoreFileOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*filestore.StoreFileParams) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
