// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import uuid "github.com/google/uuid"

// UUIDGen is an autogenerated mock type for the UUIDGen type
type UUIDGen struct {
	mock.Mock
}

// GetUUID provides a mock function with given fields:
func (_m *UUIDGen) GetUUID() uuid.UUID {
	ret := _m.Called()

	var r0 uuid.UUID
	if rf, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	return r0
}
